name: Release
on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write
  packages: write

jobs:
  build:
    name: Build JAR
    runs-on: ubuntu-latest
    steps:
      - name: Remove tag prefix
        run: |
          VERSION=${GITHUB_REF_NAME#v}
          echo "VERSION=$VERSION" >> $GITHUB_ENV
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '25'
      - name: Set pom.xml version for this release
        run: mvn -B versions:set -DnewVersion=$VERSION -DgenerateBackupPoms=false
      - name: Build jar
        run: mvn -B clean package

  publish:
    name: Publish Maven package
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Remove tag prefix
        run: |
          VERSION=${GITHUB_REF_NAME#v}
          echo "VERSION=$VERSION" >> $GITHUB_ENV
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '25'
      - name: Set pom.xml version for this release
        run: mvn -B versions:set -DnewVersion=$VERSION -DgenerateBackupPoms=false
      - name: Publish package
        run: mvn --batch-mode deploy
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  bump-pom-version-and-update-docs:
    name: Bump POMs for snapshot and update docs
    runs-on: ubuntu-latest
    needs: publish
    steps:
      - name: Remove tag prefix
        run: |
          VERSION=${GITHUB_REF_NAME#v}
          echo "VERSION=$VERSION" >> $GITHUB_ENV
      - uses: actions/checkout@v6
        with:
          ssh-key: ${{ secrets.KEY }}
      - name: Set pom.xml version for this release
        run: mvn -B versions:set -DnewVersion=$VERSION -DgenerateBackupPoms=false
      - name: Build jar
        run: mvn -B clean install
      - name: Set pom.xml snapshot version
        run: mvn -B versions:set -DnextSnapshot=true -DgenerateBackupPoms=false
      - uses: EndBug/add-and-commit@v9
        with:
          message: Bump POM and update docs
          new_branch: main
          push: true
          add: '["docs -f", "pom.xml -f"]'